### ISSUE TITLE
Support for Armatures

### ISSUE THREAD

**Issue by lyuma** [ubisoft/mixer#11]
We would like to see and edit blender Armature nodes. This would allow for making changes to the default-pose skeleton (Edit Mode); and playing an animation (Pose Mode).

Currently, mesh vertex groups are synced, and if the modifier proposal in #10 is implemented, then it will be possible to sync the Armature modifier on the Mesh object.

However, armatures are at present synced as ordinary empty nodes, with no bone data. I see two approaches:
Either, add ARMATURE message to sync the full armature (including all bones); or
Send ARMATURE metadata only, and use individual BONE_UPDATE messages to update individual bones.

Most armatures are probably small enough that they can be synced in bulk, which could simplify the implementation.

**Comment by Celeborn2BeAlive** [comment]
See my answer in #10 for detailed information about this.

**Comment by Celeborn2BeAlive** [comment]
Closing this issue because we are moving discussions to https://gitlab.com/ubisoft-animation-studio/mixer.

About Armatures, we have been informed by the developer of [multi-user](https://gitlab.com/slumber/multi-user) that the Blender API to manipulate them is quite limited (almost only operators), so it might take more time to implement their synchronization into Mixer.

@lyuma If you want to continue this discussion, please open a new issue on Gitlab, thanks !
