### ISSUE TITLE
Sync in Edit Mode

### ISSUE THREAD

**Issue by SteveSmithSoftware** [ubisoft/mixer#8]
Hi Guys, I have made a few small changes to your code to allow changes in Edit Mode to be seen in real time by other room users.
Shall I make a pull request for this or is it something you have already covered?

**Comment by fire** [comment]
I'm not a core contributor to this project, but I'd like to see it!

**Comment by Celeborn2BeAlive** [comment]
Hi @SteveSmithSoftware , thanks for experimenting with Mixer ! You can submit a pull request and we'll try to merge it as soon as possible. 
Did you tried on big meshes ? It is not too expensive ?

**Comment by SteveSmithSoftware** [comment]
> 
> 
> I'm not a core contributor to this project, but I'd like to see it!

It's still very rough around the edges but 
[mixer.zip](https://github.com/ubisoft/mixer/files/5055333/mixer.zip)

it is only small changes to the attached 3 .py files. I have commented where I have changed

**Comment by SteveSmithSoftware** [comment]
> 
> 
> Hi @SteveSmithSoftware , thanks for experimenting with Mixer ! You can submit a pull request and we'll try to merge it as soon as possible.
> Did you tried on big meshes ? It is not too expensive ?

No I haven't tried it with large meshes.
I will make it 'nice' i.e. add option to turn on and off and I will look at the socket code to see if it can be a little more efficient

**Comment by Celeborn2BeAlive** [comment]
Great, indeed an option could be required for large scenes.

Fill free to open (and update) a pull request to share your code, it will be more practical than an zip file, and also more easy for you to merge our master branch regularly. 
However if you can it would be better to fork and open the merge request on our gitlab mirror https://gitlab.com/ubisoft-animation-studio/mixer since we do our daily devs in a gitlab instance (we can also run tests, lint, etc on it thanks to our Gitlab CI script). Not strictly required though, if you prefer Github that's ok.

**Comment by Celeborn2BeAlive** [comment]
Closing this issue because we are moving discussions to https://gitlab.com/ubisoft-animation-studio/mixer.

@SteveSmithSoftwareIf you want to continue this discussion, please open a new issue on Gitlab, thanks ! Also you can open a merge request on it if you want us to review your changes and integrate them (be sure to make it optional though since edit mode sync can be expensive)
